### ISSUE TITLE
Consider either turning off auto-sharding or switching the auto_shard_policy to DATA

### ISSUE THREAD

**Issue by LouiValley** [sayakpaul/MLP-Mixer-CIFAR10#2]
Excuse me, when I try to run it on the serve, it tips:

Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
2021-11-21 11:59:20.861052: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.

BTW, my TensorFlow version is 2.4.0, how to fix this problem?

**Comment by sayakpaul** [comment]
You can ignore the problem. Prefer running the code on Google Colab which always has the latest stable version (currently 2.7) of TensorFlow pre-installed.
