### ISSUE TITLE
Why the accuracy drops after epoch 100/100 (accuracy drops from 91% to 71%)

### ISSUE THREAD

**Issue by LouiValley** [sayakpaul/MLP-Mixer-CIFAR10#3]
I trained the Network ( NUM_MIXER_LAYERS =4 )

At epoch 100:

Epoch 100/100

 1/44 [..............................] - ETA: 1s - loss: 0.2472 - accuracy: 0.9160
 3/44 [=>............................] - ETA: 1s - loss: 0.2424 - accuracy: 0.9162
 5/44 [==>...........................] - ETA: 1s - loss: 0.2431 - accuracy: 0.9155
 7/44 [===>..........................] - ETA: 1s - loss: 0.2424 - accuracy: 0.9154
 9/44 [=====>........................] - ETA: 1s - loss: 0.2419 - accuracy: 0.9155
11/44 [======>.......................] - ETA: 1s - loss: 0.2423 - accuracy: 0.9150
13/44 [=======>......................] - ETA: 1s - loss: 0.2426 - accuracy: 0.9145
15/44 [=========>....................] - ETA: 1s - loss: 0.2430 - accuracy: 0.9142
17/44 [==========>...................] - ETA: 1s - loss: 0.2433 - accuracy: 0.9140
19/44 [===========>..................] - ETA: 1s - loss: 0.2435 - accuracy: 0.9138
21/44 [=============>................] - ETA: 0s - loss: 0.2438 - accuracy: 0.9136
23/44 [==============>...............] - ETA: 0s - loss: 0.2439 - accuracy: 0.9135
25/44 [================>.............] - ETA: 0s - loss: 0.2440 - accuracy: 0.9134
27/44 [=================>............] - ETA: 0s - loss: 0.2440 - accuracy: 0.9133
29/44 [==================>...........] - ETA: 0s - loss: 0.2442 - accuracy: 0.9132
31/44 [====================>.........] - ETA: 0s - loss: 0.2445 - accuracy: 0.9130
33/44 [=====================>........] - ETA: 0s - loss: 0.2447 - accuracy: 0.9129
35/44 [======================>.......] - ETA: 0s - loss: 0.2450 - accuracy: 0.9127
37/44 [========================>.....] - ETA: 0s - loss: 0.2454 - accuracy: 0.9125
39/44 [=========================>....] - ETA: 0s - loss: 0.2459 - accuracy: 0.9123
41/44 [==========================>...] - ETA: 0s - loss: 0.2463 - accuracy: 0.9121
43/44 [============================>.] - ETA: 0s - loss: 0.2469 - accuracy: 0.9119
44/44 [==============================] - 2s 46ms/step - loss: 0.2474 - accuracy: **0.9117** - val_loss: 1.1145 - val_accuracy: 0.7226

Then it still have an extra training,
 1/313 [..............................] - ETA: 24:32 - loss: 0.5860 - accuracy: 0.8125
 8/313 [..............................] - ETA: 2s - loss: 1.2071 - accuracy: 0.6953   
.....
313/313 [==============================] - ETA: 0s - loss: 1.0934 - accuracy: 0.7161
313/313 [==============================] - 12s 22ms/step - loss: 1.0934 - accuracy: 0.7161
Test accuracy: **71.61**

**Comment by sayakpaul** [comment]
That is not training. That is an evaluation after training and what you see is because of the verbosity.
